### PR TITLE
Fix tests to use React Router

### PR DESCRIPTION
**Pull request by kristinaxlee**

### CODE REVIEW

**Review by Ruefa — CHANGES_REQUESTED** [review]
I'd hate to ask you to do this all again but your implementation is not [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself). A better way to do this would be to write a helper function `renderBrowser` that works almost the same as `render` but it wraps the component in `<BrowserRouter>` so you don't need to repeat that part.

**Comment by kristinaxlee** [comment]
Added a new test util function called ```renderWithRouter``` which wraps the render function in a <BrowserRouter> tag.

**Comment by kristinaxlee** [comment]
Added a new test util function called renderWithRouter which wraps the render function in a tag.

**Comment by kristinaxlee** [comment]
> I'd hate to ask you to do this all again but your implementation is not [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself). A better way to do this would be to write a helper function `renderBrowser` that works almost the same as `render` but it wraps the component in `<BrowserRouter>` so you don't need to repeat that part.

Added a new test util function called renderWithRouter which wraps the render function in a tag.

**Review by Ruefa — APPROVED** [review]

**Pull request merged**
